-- CreateTable
CREATE TABLE "cards" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "oracle_id" TEXT NOT NULL,
    "multiverse_ids" JSONB NOT NULL,
    "mtgo_id" INTEGER,
    "tcgplayer_id" INTEGER,
    "cardmarket_id" INTEGER,
    "name" TEXT NOT NULL,
    "lang" TEXT NOT NULL,
    "released_at" DATETIME NOT NULL,
    "uri" TEXT NOT NULL,
    "scryfall_uri" TEXT NOT NULL,
    "layout" TEXT NOT NULL,
    "highres_image" BOOLEAN NOT NULL,
    "image_status" TEXT NOT NULL,
    "image_uris" JSONB,
    "mana_cost" TEXT,
    "cmc" REAL NOT NULL,
    "type_line" TEXT NOT NULL,
    "oracle_text" TEXT,
    "power" TEXT,
    "toughness" TEXT,
    "colors" JSONB NOT NULL DEFAULT [],
    "color_identity" JSONB NOT NULL DEFAULT [],
    "keywords" JSONB NOT NULL DEFAULT [],
    "all_parts" JSONB,
    "legalities" JSONB NOT NULL,
    "games" JSONB NOT NULL DEFAULT [],
    "reserved" BOOLEAN NOT NULL,
    "game_changer" BOOLEAN NOT NULL,
    "foil" BOOLEAN NOT NULL,
    "nonfoil" BOOLEAN NOT NULL,
    "finishes" JSONB NOT NULL DEFAULT [],
    "oversized" BOOLEAN NOT NULL,
    "promo" BOOLEAN NOT NULL,
    "reprint" BOOLEAN NOT NULL,
    "variation" BOOLEAN NOT NULL,
    "set_id" TEXT NOT NULL,
    "set" TEXT NOT NULL,
    "set_name" TEXT NOT NULL,
    "set_type" TEXT NOT NULL,
    "set_uri" TEXT NOT NULL,
    "set_search_uri" TEXT NOT NULL,
    "scryfall_set_uri" TEXT NOT NULL,
    "rulings_uri" TEXT NOT NULL,
    "prints_search_uri" TEXT NOT NULL,
    "collector_number" TEXT NOT NULL,
    "digital" BOOLEAN NOT NULL,
    "rarity" TEXT NOT NULL,
    "watermark" TEXT,
    "flavor_text" TEXT,
    "card_back_id" TEXT NOT NULL,
    "artist" TEXT NOT NULL,
    "artist_ids" JSONB NOT NULL DEFAULT [],
    "illustration_id" TEXT,
    "border_color" TEXT NOT NULL,
    "frame" TEXT NOT NULL,
    "frame_effects" JSONB NOT NULL DEFAULT [],
    "security_stamp" TEXT,
    "full_art" BOOLEAN NOT NULL,
    "textless" BOOLEAN NOT NULL,
    "booster" BOOLEAN NOT NULL,
    "story_spotlight" BOOLEAN NOT NULL,
    "edhrec_rank" INTEGER,
    "preview" JSONB,
    "prices" JSONB NOT NULL,
    "related_uris" JSONB NOT NULL,
    "purchase_uris" JSONB NOT NULL,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "decks" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "format" TEXT,
    "colors" JSONB NOT NULL DEFAULT [],
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL
);
